import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/Navbar/Navbar";
import Footer from "./Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col `}>
        {/* Navbar siempre al principio */}
        <Navbar />
        
        {/* Main que crece para llenar el espacio disponible */}
        <main className="flex-grow w-full">
          {children}
        </main>
        
        {/* Footer siempre al final */}
        <Footer />
      </body>
    </html>
  );
}
